print("-"*35)
print(" MY PERSONAL BIO GENERATOR")
print("-"*35)
name = input("Enter your name:")
hobby = input("Enter your hobby:")
food = input("Enter your favourite food:")
dream_job = input("Enter your dream job:")
print("\n")
print("-" * 35)
print(" MY BIO")
print("-" * 35)
print("My name is ", name)
print ("I love", hobby)
print("My favourite food is", food)
print("My dream is to become ",dream_job)