print("=" * 35)
print("  SIMPLE CALCULATOR")
print("=" * 35)
num1 = int(input("Enter First Number: "))
num2 =int(input("Enter Second Number: "))
print("/n")
print("Addition =",num1 + num2 )
print("Subtraction=",num1 - num2 )
print("Muliplication=",num1*num2)
print("Division=",num1/num2)