print("=" *35)
print(" STUDENT PROFILE")
print("=" *35)
name = input("enter your name:")
college = input("enter your college name:")
branch = input("enter your branch:")
age = input("enter your age:")
city =input("enter your city:")
dream  = input("enter your dream job:")
print("\n")
print("=" *35)
print(" STUDENT PROFILE")
print("="*35)
print("Name:",name)
print("College:",college)
print("Branch:",branch)
print("Age:",age)
print("City:",city)
print("Dream Job:",dream )
print("\n Welcome to My Coding Journey!")